
const restaurants = [
  'The Bird',
  'Lao Table',
  'Tropisueno',
  'Marlowe',
  'Tacorea',
  'Kin Khoa',
  'HRD',
  'Box Kitchen',
  'Littke Delhi',
  'Donburi Ya',
  'Tin Vietnamese Cruisine',
  'The House',
  'Deli Board',
  'Cockcomb',
  'Liholiho Yacht CLub',
  'The Pink Elephant Alibi',
  'Dumpling Time',
  'Barcha',
  'Voodoo Love',
  'Tselogs',
  'Garaje',
  'SF Chickenbox',
  'Hogwash',
  'Hog Island Oyster Co',
  'Delarosa',
  'Bluestem Brasserie',
  'Braised + Bread',
  'Aria Korean Street Food',
  'M.Y. China',
  'Gozu',
  'North India Restaurant',
  'Rooter & Rice',
  'Fayala',
  'Golden Burma',
  'The Flying Falafel',
  'Freshroll Vietnamese Rools & Bowls',
  'Mensho Tokyo',
  'Fondue Cowboy',
  'Sowl Bowls Thai Street Food',
  'Burma Club',
  'The Pawn Shop',
  'Benu',
  'Urabn Tavern',
  'Per Diem',
  'Rooftop 25', 
  'Little Creatures Mission Bay',
  'Saap Ver Authentic Thai Cruisine',
  'Trailbazer Tavern',
  'The View Lounge',
  'Garajito',
  'Falafelland',
  'DragonEats',
  'Honey Honey Cafe and Crepery',
  'Sababa',
  'Tu Lan',
  'Barnzu',
  'Basil Thai Restaurnat & Bar',
  'Thirty Bear Brewing Company',
  'HoM Korean Kitchen',
  'Bask',
  'Tsuta Japanese Soba Noodles',
  'Skool',
  'E&O Kitchen and Bar',
  'Saffron 685',
  'Colibri Mexican Bistro',
  'Lord George',
  'Birdsong',
  'Wayfare Tavern',
  'Haskashi Japanese Bar & Grill',
  'RM 212',
  'Troya Soma',
  'Sanraku',
  'Uno Dos Tacos',
  'Lucky Pig',
  'Square Pie Guys',
  'Z & Y Restaurant',
  'Kokkari Estiatorio',
  'Rooster & Rice',
  'The Rotunda',
  'Sun and Moon',
  'Matador',
  'Jin Mi Korean Cuisine',
  'Kiss My Seoul',
  'Hopwater Distribution',
  'Deli Board',
  'Palette SF',
  'The Keystone',
  'Miss SaiGon',
  'Lucky Pig',
  'The Cavalier',
  'Takoba SF',
  'Fringale',
  'Bota Tapas & Paella Bar',
  '54 Mint - Ristorante Italiano'

];

exports.restaurants = restaurants;